/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ARCHIVE_EXTENSIONS: typeof import('./lib/local-mod-import').ARCHIVE_EXTENSIONS
  const AppAnalytics: typeof import('./lib/Analytics').AppAnalytics
  const Aria2: typeof import('./lib/aria2').Aria2
  const Aria2Rpc: typeof import('./lib/aria2-rpc').Aria2Rpc
  const AutoStart: typeof import('./lib/auto-start').AutoStart
  const EMBEDDED_TOOL_VERSIONS: typeof import('./lib/native-tools-manifest').EMBEDDED_TOOL_VERSIONS
  const EffectScope: typeof import('vue').EffectScope
  const FileHandler: typeof import('./lib/FileHandler').FileHandler
  const Manager: typeof import('./lib/Manager').Manager
  const NativeToolsManifest: typeof import('./lib/native-tools-manifest').NativeToolsManifest
  const PersistentStore: typeof import('./lib/persistent-store').PersistentStore
  const SIDECAR_BASE_NAMES: typeof import('./lib/native-tools-manifest').SIDECAR_BASE_NAMES
  const SIDECAR_COMMANDS: typeof import('./lib/native-tools-manifest').SIDECAR_COMMANDS
  const ScanGame: typeof import('./lib/scan-game').ScanGame
  const SevenZip: typeof import('./lib/sevenZip').SevenZip
  const Sidecar: typeof import('./lib/sidecar').Sidecar
  const SidecarExecutionError: typeof import('./lib/sidecar').SidecarExecutionError
  const Theme: typeof import('./lib/theme').Theme
  const UnityGame: typeof import('./lib/UnityGame').UnityGame
  const UnityGameILCPP2: typeof import('./lib/UnityGame').UnityGameILCPP2
  const UnrealEngine: typeof import('./lib/UnrealEngine').UnrealEngine
  const WINDOWS_SEVEN_ZIP_SUPPORT_FILES: typeof import('./lib/native-tools-manifest').WINDOWS_SEVEN_ZIP_SUPPORT_FILES
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const asyncComputed: typeof import('@vueuse/core').asyncComputed
  const autoResetRef: typeof import('@vueuse/core').autoResetRef
  const buildAria2DownloadArgs: typeof import('./lib/aria2').buildAria2DownloadArgs
  const buildAria2RpcServerArgs: typeof import('./lib/aria2').buildAria2RpcServerArgs
  const buildUniqueGlossFileName: typeof import('./lib/gloss-download').buildUniqueGlossFileName
  const cn: typeof import('./lib/utils').cn
  const computed: typeof import('vue').computed
  const computedAsync: typeof import('@vueuse/core').computedAsync
  const computedEager: typeof import('@vueuse/core').computedEager
  const computedInject: typeof import('@vueuse/core').computedInject
  const computedWithControl: typeof import('@vueuse/core').computedWithControl
  const controlledComputed: typeof import('@vueuse/core').controlledComputed
  const controlledRef: typeof import('@vueuse/core').controlledRef
  const createApp: typeof import('vue').createApp
  const createArchiveWithSevenZip: typeof import('./lib/sevenZip').createArchiveWithSevenZip
  const createEventHook: typeof import('@vueuse/core').createEventHook
  const createGlobalState: typeof import('@vueuse/core').createGlobalState
  const createInjectionState: typeof import('@vueuse/core').createInjectionState
  const createPinia: typeof import('pinia').createPinia
  const createReactiveFn: typeof import('@vueuse/core').createReactiveFn
  const createRef: typeof import('@vueuse/core').createRef
  const createReusableTemplate: typeof import('@vueuse/core').createReusableTemplate
  const createSharedComposable: typeof import('@vueuse/core').createSharedComposable
  const createTemplatePromise: typeof import('@vueuse/core').createTemplatePromise
  const createUnrefFn: typeof import('@vueuse/core').createUnrefFn
  const customRef: typeof import('vue').customRef
  const debouncedRef: typeof import('@vueuse/core').debouncedRef
  const debouncedWatch: typeof import('@vueuse/core').debouncedWatch
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const downloadWithAria2: typeof import('./lib/aria2').downloadWithAria2
  const eagerComputed: typeof import('@vueuse/core').eagerComputed
  const effectScope: typeof import('vue').effectScope
  const executeAria2Sidecar: typeof import('./lib/sidecar').executeAria2Sidecar
  const executeSevenZipSidecar: typeof import('./lib/sidecar').executeSevenZipSidecar
  const executeSidecar: typeof import('./lib/sidecar').executeSidecar
  const extendRef: typeof import('@vueuse/core').extendRef
  const extractArchiveWithSevenZip: typeof import('./lib/sevenZip').extractArchiveWithSevenZip
  const findGlossDuplicateLocalMods: typeof import('./lib/gloss-download').findGlossDuplicateLocalMods
  const findGlossDuplicateTasks: typeof import('./lib/gloss-download').findGlossDuplicateTasks
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getGlossModPresence: typeof import('./lib/gloss-download').getGlossModPresence
  const h: typeof import('vue').h
  const hydrateManagerRuntimeData: typeof import('./lib/manager-runtime-data').hydrateManagerRuntimeData
  const ignorableWatch: typeof import('@vueuse/core').ignorableWatch
  const importLocalModSources: typeof import('./lib/local-mod-import').importLocalModSources
  const init: typeof import('./lib/global').init
  const initializeAutoStart: typeof import('./lib/auto-start').initializeAutoStart
  const initializeTheme: typeof import('./lib/theme').initializeTheme
  const inject: typeof import('vue').inject
  const injectLocal: typeof import('@vueuse/core').injectLocal
  const isDefined: typeof import('@vueuse/core').isDefined
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const listArchiveWithSevenZip: typeof import('./lib/sevenZip').listArchiveWithSevenZip
  const makeDestructurable: typeof import('@vueuse/core').makeDestructurable
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const normalizeCompareText: typeof import('./lib/gloss-download').normalizeCompareText
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onClickOutside: typeof import('@vueuse/core').onClickOutside
  const onDeactivated: typeof import('vue').onDeactivated
  const onElementRemoval: typeof import('@vueuse/core').onElementRemoval
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onKeyStroke: typeof import('@vueuse/core').onKeyStroke
  const onLongPress: typeof import('@vueuse/core').onLongPress
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onStartTyping: typeof import('@vueuse/core').onStartTyping
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const pausableWatch: typeof import('@vueuse/core').pausableWatch
  const provide: typeof import('vue').provide
  const provideLocal: typeof import('@vueuse/core').provideLocal
  const reactify: typeof import('@vueuse/core').reactify
  const reactifyObject: typeof import('@vueuse/core').reactifyObject
  const reactive: typeof import('vue').reactive
  const reactiveComputed: typeof import('@vueuse/core').reactiveComputed
  const reactiveOmit: typeof import('@vueuse/core').reactiveOmit
  const reactivePick: typeof import('@vueuse/core').reactivePick
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const refAutoReset: typeof import('@vueuse/core').refAutoReset
  const refDebounced: typeof import('@vueuse/core').refDebounced
  const refDefault: typeof import('@vueuse/core').refDefault
  const refManualReset: typeof import('@vueuse/core').refManualReset
  const refThrottled: typeof import('@vueuse/core').refThrottled
  const refWithControl: typeof import('@vueuse/core').refWithControl
  const resolveComponent: typeof import('vue').resolveComponent
  const resolveLocalModImportSourceType: typeof import('./lib/local-mod-import').resolveLocalModImportSourceType
  const resolveRef: typeof import('@vueuse/core').resolveRef
  const runAria2Command: typeof import('./lib/aria2').runAria2Command
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const setTheme: typeof import('./lib/theme').setTheme
  const settingsStartPageOptions: typeof import('./stores/settings').settingsStartPageOptions
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const spawnAria2Download: typeof import('./lib/aria2').spawnAria2Download
  const spawnAria2Sidecar: typeof import('./lib/sidecar').spawnAria2Sidecar
  const spawnSidecar: typeof import('./lib/sidecar').spawnSidecar
  const startAria2RpcServer: typeof import('./lib/aria2').startAria2RpcServer
  const storeToRefs: typeof import('pinia').storeToRefs
  const syncManagerRuntimeContext: typeof import('./lib/manager-context').syncManagerRuntimeContext
  const syncRef: typeof import('@vueuse/core').syncRef
  const syncRefs: typeof import('@vueuse/core').syncRefs
  const templateRef: typeof import('@vueuse/core').templateRef
  const testArchiveWithSevenZip: typeof import('./lib/sevenZip').testArchiveWithSevenZip
  const throttledRef: typeof import('@vueuse/core').throttledRef
  const throttledWatch: typeof import('@vueuse/core').throttledWatch
  const toRaw: typeof import('vue').toRaw
  const toReactive: typeof import('@vueuse/core').toReactive
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const tryOnBeforeMount: typeof import('@vueuse/core').tryOnBeforeMount
  const tryOnBeforeUnmount: typeof import('@vueuse/core').tryOnBeforeUnmount
  const tryOnMounted: typeof import('@vueuse/core').tryOnMounted
  const tryOnScopeDispose: typeof import('@vueuse/core').tryOnScopeDispose
  const tryOnUnmounted: typeof import('@vueuse/core').tryOnUnmounted
  const unref: typeof import('vue').unref
  const unrefElement: typeof import('@vueuse/core').unrefElement
  const until: typeof import('@vueuse/core').until
  const useActiveElement: typeof import('@vueuse/core').useActiveElement
  const useAnimate: typeof import('@vueuse/core').useAnimate
  const useArrayDifference: typeof import('@vueuse/core').useArrayDifference
  const useArrayEvery: typeof import('@vueuse/core').useArrayEvery
  const useArrayFilter: typeof import('@vueuse/core').useArrayFilter
  const useArrayFind: typeof import('@vueuse/core').useArrayFind
  const useArrayFindIndex: typeof import('@vueuse/core').useArrayFindIndex
  const useArrayFindLast: typeof import('@vueuse/core').useArrayFindLast
  const useArrayIncludes: typeof import('@vueuse/core').useArrayIncludes
  const useArrayJoin: typeof import('@vueuse/core').useArrayJoin
  const useArrayMap: typeof import('@vueuse/core').useArrayMap
  const useArrayReduce: typeof import('@vueuse/core').useArrayReduce
  const useArraySome: typeof import('@vueuse/core').useArraySome
  const useArrayUnique: typeof import('@vueuse/core').useArrayUnique
  const useAsyncQueue: typeof import('@vueuse/core').useAsyncQueue
  const useAsyncState: typeof import('@vueuse/core').useAsyncState
  const useAttrs: typeof import('vue').useAttrs
  const useAutoStart: typeof import('./lib/auto-start').useAutoStart
  const useBase64: typeof import('@vueuse/core').useBase64
  const useBattery: typeof import('@vueuse/core').useBattery
  const useBluetooth: typeof import('@vueuse/core').useBluetooth
  const useBreakpoints: typeof import('@vueuse/core').useBreakpoints
  const useBroadcastChannel: typeof import('@vueuse/core').useBroadcastChannel
  const useBrowserLocation: typeof import('@vueuse/core').useBrowserLocation
  const useCached: typeof import('@vueuse/core').useCached
  const useClipboard: typeof import('@vueuse/core').useClipboard
  const useClipboardItems: typeof import('@vueuse/core').useClipboardItems
  const useCloned: typeof import('@vueuse/core').useCloned
  const useColorMode: typeof import('@vueuse/core').useColorMode
  const useConfirmDialog: typeof import('@vueuse/core').useConfirmDialog
  const useCountdown: typeof import('@vueuse/core').useCountdown
  const useCounter: typeof import('@vueuse/core').useCounter
  const useCssModule: typeof import('vue').useCssModule
  const useCssSupports: typeof import('@vueuse/core').useCssSupports
  const useCssVar: typeof import('@vueuse/core').useCssVar
  const useCssVars: typeof import('vue').useCssVars
  const useCurrentElement: typeof import('@vueuse/core').useCurrentElement
  const useCycleList: typeof import('@vueuse/core').useCycleList
  const useDark: typeof import('@vueuse/core').useDark
  const useDateFormat: typeof import('@vueuse/core').useDateFormat
  const useDebounce: typeof import('@vueuse/core').useDebounce
  const useDebounceFn: typeof import('@vueuse/core').useDebounceFn
  const useDebouncedRefHistory: typeof import('@vueuse/core').useDebouncedRefHistory
  const useDeviceMotion: typeof import('@vueuse/core').useDeviceMotion
  const useDeviceOrientation: typeof import('@vueuse/core').useDeviceOrientation
  const useDevicePixelRatio: typeof import('@vueuse/core').useDevicePixelRatio
  const useDevicesList: typeof import('@vueuse/core').useDevicesList
  const useDisplayMedia: typeof import('@vueuse/core').useDisplayMedia
  const useDocumentVisibility: typeof import('@vueuse/core').useDocumentVisibility
  const useDraggable: typeof import('@vueuse/core').useDraggable
  const useDropZone: typeof import('@vueuse/core').useDropZone
  const useElementBounding: typeof import('@vueuse/core').useElementBounding
  const useElementByPoint: typeof import('@vueuse/core').useElementByPoint
  const useElementHover: typeof import('@vueuse/core').useElementHover
  const useElementSize: typeof import('@vueuse/core').useElementSize
  const useElementVisibility: typeof import('@vueuse/core').useElementVisibility
  const useEventBus: typeof import('@vueuse/core').useEventBus
  const useEventListener: typeof import('@vueuse/core').useEventListener
  const useEventSource: typeof import('@vueuse/core').useEventSource
  const useEyeDropper: typeof import('@vueuse/core').useEyeDropper
  const useFavicon: typeof import('@vueuse/core').useFavicon
  const useFetch: typeof import('@vueuse/core').useFetch
  const useFileDialog: typeof import('@vueuse/core').useFileDialog
  const useFileSystemAccess: typeof import('@vueuse/core').useFileSystemAccess
  const useFocus: typeof import('@vueuse/core').useFocus
  const useFocusWithin: typeof import('@vueuse/core').useFocusWithin
  const useFps: typeof import('@vueuse/core').useFps
  const useFullscreen: typeof import('@vueuse/core').useFullscreen
  const useGamepad: typeof import('@vueuse/core').useGamepad
  const useGeolocation: typeof import('@vueuse/core').useGeolocation
  const useId: typeof import('vue').useId
  const useIdle: typeof import('@vueuse/core').useIdle
  const useImage: typeof import('@vueuse/core').useImage
  const useInfiniteScroll: typeof import('@vueuse/core').useInfiniteScroll
  const useIntersectionObserver: typeof import('@vueuse/core').useIntersectionObserver
  const useInterval: typeof import('@vueuse/core').useInterval
  const useIntervalFn: typeof import('@vueuse/core').useIntervalFn
  const useKeyModifier: typeof import('@vueuse/core').useKeyModifier
  const useLastChanged: typeof import('@vueuse/core').useLastChanged
  const useLauncherStore: typeof import('./stores/launcher').useLauncherStore
  const useLink: typeof import('vue-router').useLink
  const useLocalStorage: typeof import('@vueuse/core').useLocalStorage
  const useMagicKeys: typeof import('@vueuse/core').useMagicKeys
  const useManager: typeof import('./stores/manager').useManager
  const useManualRefHistory: typeof import('@vueuse/core').useManualRefHistory
  const useMediaControls: typeof import('@vueuse/core').useMediaControls
  const useMediaQuery: typeof import('@vueuse/core').useMediaQuery
  const useMemoize: typeof import('@vueuse/core').useMemoize
  const useMemory: typeof import('@vueuse/core').useMemory
  const useModel: typeof import('vue').useModel
  const useMounted: typeof import('@vueuse/core').useMounted
  const useMouse: typeof import('@vueuse/core').useMouse
  const useMouseInElement: typeof import('@vueuse/core').useMouseInElement
  const useMousePressed: typeof import('@vueuse/core').useMousePressed
  const useMutationObserver: typeof import('@vueuse/core').useMutationObserver
  const useNavigatorLanguage: typeof import('@vueuse/core').useNavigatorLanguage
  const useNetwork: typeof import('@vueuse/core').useNetwork
  const useNow: typeof import('@vueuse/core').useNow
  const useObjectUrl: typeof import('@vueuse/core').useObjectUrl
  const useOffsetPagination: typeof import('@vueuse/core').useOffsetPagination
  const useOnline: typeof import('@vueuse/core').useOnline
  const usePageLeave: typeof import('@vueuse/core').usePageLeave
  const useParallax: typeof import('@vueuse/core').useParallax
  const useParentElement: typeof import('@vueuse/core').useParentElement
  const usePerformanceObserver: typeof import('@vueuse/core').usePerformanceObserver
  const usePermission: typeof import('@vueuse/core').usePermission
  const usePointer: typeof import('@vueuse/core').usePointer
  const usePointerLock: typeof import('@vueuse/core').usePointerLock
  const usePointerSwipe: typeof import('@vueuse/core').usePointerSwipe
  const usePreferredColorScheme: typeof import('@vueuse/core').usePreferredColorScheme
  const usePreferredContrast: typeof import('@vueuse/core').usePreferredContrast
  const usePreferredDark: typeof import('@vueuse/core').usePreferredDark
  const usePreferredLanguages: typeof import('@vueuse/core').usePreferredLanguages
  const usePreferredReducedMotion: typeof import('@vueuse/core').usePreferredReducedMotion
  const usePreferredReducedTransparency: typeof import('@vueuse/core').usePreferredReducedTransparency
  const usePrevious: typeof import('@vueuse/core').usePrevious
  const useRafFn: typeof import('@vueuse/core').useRafFn
  const useRefHistory: typeof import('@vueuse/core').useRefHistory
  const useResizeObserver: typeof import('@vueuse/core').useResizeObserver
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSSRWidth: typeof import('@vueuse/core').useSSRWidth
  const useScreenOrientation: typeof import('@vueuse/core').useScreenOrientation
  const useScreenSafeArea: typeof import('@vueuse/core').useScreenSafeArea
  const useScriptTag: typeof import('@vueuse/core').useScriptTag
  const useScroll: typeof import('@vueuse/core').useScroll
  const useScrollLock: typeof import('@vueuse/core').useScrollLock
  const useSessionStorage: typeof import('@vueuse/core').useSessionStorage
  const useSettings: typeof import('./stores/settings').useSettings
  const useShare: typeof import('@vueuse/core').useShare
  const useSlots: typeof import('vue').useSlots
  const useSorted: typeof import('@vueuse/core').useSorted
  const useSpeechRecognition: typeof import('@vueuse/core').useSpeechRecognition
  const useSpeechSynthesis: typeof import('@vueuse/core').useSpeechSynthesis
  const useStepper: typeof import('@vueuse/core').useStepper
  const useStorage: typeof import('@vueuse/core').useStorage
  const useStorageAsync: typeof import('@vueuse/core').useStorageAsync
  const useStyleTag: typeof import('@vueuse/core').useStyleTag
  const useSupported: typeof import('@vueuse/core').useSupported
  const useSwipe: typeof import('@vueuse/core').useSwipe
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTemplateRefsList: typeof import('@vueuse/core').useTemplateRefsList
  const useTextDirection: typeof import('@vueuse/core').useTextDirection
  const useTextSelection: typeof import('@vueuse/core').useTextSelection
  const useTextareaAutosize: typeof import('@vueuse/core').useTextareaAutosize
  const useTheme: typeof import('./lib/theme').useTheme
  const useThrottle: typeof import('@vueuse/core').useThrottle
  const useThrottleFn: typeof import('@vueuse/core').useThrottleFn
  const useThrottledRefHistory: typeof import('@vueuse/core').useThrottledRefHistory
  const useTimeAgo: typeof import('@vueuse/core').useTimeAgo
  const useTimeAgoIntl: typeof import('@vueuse/core').useTimeAgoIntl
  const useTimeout: typeof import('@vueuse/core').useTimeout
  const useTimeoutFn: typeof import('@vueuse/core').useTimeoutFn
  const useTimeoutPoll: typeof import('@vueuse/core').useTimeoutPoll
  const useTimestamp: typeof import('@vueuse/core').useTimestamp
  const useTitle: typeof import('@vueuse/core').useTitle
  const useToNumber: typeof import('@vueuse/core').useToNumber
  const useToString: typeof import('@vueuse/core').useToString
  const useToggle: typeof import('@vueuse/core').useToggle
  const useTransition: typeof import('@vueuse/core').useTransition
  const useUrlSearchParams: typeof import('@vueuse/core').useUrlSearchParams
  const useUserMedia: typeof import('@vueuse/core').useUserMedia
  const useVModel: typeof import('@vueuse/core').useVModel
  const useVModels: typeof import('@vueuse/core').useVModels
  const useVibrate: typeof import('@vueuse/core').useVibrate
  const useVirtualList: typeof import('@vueuse/core').useVirtualList
  const useWakeLock: typeof import('@vueuse/core').useWakeLock
  const useWebNotification: typeof import('@vueuse/core').useWebNotification
  const useWebSocket: typeof import('@vueuse/core').useWebSocket
  const useWebWorker: typeof import('@vueuse/core').useWebWorker
  const useWebWorkerFn: typeof import('@vueuse/core').useWebWorkerFn
  const useWindowFocus: typeof import('@vueuse/core').useWindowFocus
  const useWindowScroll: typeof import('@vueuse/core').useWindowScroll
  const useWindowSize: typeof import('@vueuse/core').useWindowSize
  const watch: typeof import('vue').watch
  const watchArray: typeof import('@vueuse/core').watchArray
  const watchAtMost: typeof import('@vueuse/core').watchAtMost
  const watchDebounced: typeof import('@vueuse/core').watchDebounced
  const watchDeep: typeof import('@vueuse/core').watchDeep
  const watchEffect: typeof import('vue').watchEffect
  const watchIgnorable: typeof import('@vueuse/core').watchIgnorable
  const watchImmediate: typeof import('@vueuse/core').watchImmediate
  const watchOnce: typeof import('@vueuse/core').watchOnce
  const watchPausable: typeof import('@vueuse/core').watchPausable
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
  const watchThrottled: typeof import('@vueuse/core').watchThrottled
  const watchTriggerable: typeof import('@vueuse/core').watchTriggerable
  const watchWithFilter: typeof import('@vueuse/core').watchWithFilter
  const whenever: typeof import('@vueuse/core').whenever
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { AppAnalytics } from './lib/Analytics'
  import('./lib/Analytics')
  // @ts-ignore
  export type { FileHandler } from './lib/FileHandler'
  import('./lib/FileHandler')
  // @ts-ignore
  export type { Manager } from './lib/Manager'
  import('./lib/Manager')
  // @ts-ignore
  export type { UnityGame, UnityGameILCPP2 } from './lib/UnityGame'
  import('./lib/UnityGame')
  // @ts-ignore
  export type { UnrealEngine } from './lib/UnrealEngine'
  import('./lib/UnrealEngine')
  // @ts-ignore
  export type { Aria2Rpc, IAria2RpcTaskUri, IAria2RpcTaskFile, IAria2RpcTask, IAria2GlobalStat, IAria2RpcEnsureOptions, IAria2RuntimeSettings } from './lib/aria2-rpc'
  import('./lib/aria2-rpc')
  // @ts-ignore
  export type { Aria2, Aria2DownloadOptions, Aria2RpcServerOptions } from './lib/aria2'
  import('./lib/aria2')
  // @ts-ignore
  export type { AutoStart } from './lib/auto-start'
  import('./lib/auto-start')
  // @ts-ignore
  export type { IGlossDownloadTaskMeta, GlossDownloadPresence, IGlossDuplicateCriteria, IGlossDuplicateTaskMatch, IGlossDuplicateLocalModMatch } from './lib/gloss-download'
  import('./lib/gloss-download')
  // @ts-ignore
  export type { LocalModImportSourceType, LocalModImportDuplicateStrategy, ILocalModImportSource } from './lib/local-mod-import'
  import('./lib/local-mod-import')
  // @ts-ignore
  export type { NativeToolsManifest, EmbeddedToolName, EmbeddedSidecarCommand } from './lib/native-tools-manifest'
  import('./lib/native-tools-manifest')
  // @ts-ignore
  export type { PersistentStore } from './lib/persistent-store'
  import('./lib/persistent-store')
  // @ts-ignore
  export type { ScanGame } from './lib/scan-game'
  import('./lib/scan-game')
  // @ts-ignore
  export type { SevenZip, SevenZipOverwriteMode, SevenZipArchiveFormat, SevenZipExtractOptions, SevenZipCreateOptions, SevenZipListOptions, SevenZipTestOptions, SevenZipArchiveEntry, SevenZipListResult } from './lib/sevenZip'
  import('./lib/sevenZip')
  // @ts-ignore
  export type { SidecarExecutionError, Sidecar, SidecarCommandOptions, SidecarResult, SpawnedSidecarProcess } from './lib/sidecar'
  import('./lib/sidecar')
  // @ts-ignore
  export type { Theme, ThemeMode } from './lib/theme'
  import('./lib/theme')
}
