name: Build Electron App
on:
  push:
    branches:
      - master
    tags:
      - "v*"
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: |
          yarn
      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn run build
      - name: Upload artifact 1
        uses: actions/upload-artifact@v2
        with:
          name: GlossModManager
          path: ./release/1.0.0/win-unpacked
      - name: Upload artifact 2
        uses: actions/upload-artifact@v2
        with:
          name: GlossModManager.exe
          path: ./release/1.0.0/gloss-mod-manager_1.0.0.exe
