name: Build Electron App
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Zip files
        run: |
          mkdir dist
          cd dist
          zip -r ../electron-app.zip .
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: electron-app
          path: electron-app.zip